/**
 * CORPUS VALIDATION RUNNER (v3 prompt 11, ADR-0034; blocking CI job `corpus`) -
 * `pnpm corpus:validate`.
 *
 * Regenerates the corpus from the hand-owned spec, byte-compares it against the
 * committed tree, and re-checks every corpus rule: provenance labels, closed
 * defect taxonomy, disjointness from the signed golden set, timestamp realism,
 * NFC canonical identity, the fail-closed real-derived intake contract, and
 * signoff binding to `corpusDigest`.
 *
 * The same core runs inside `pnpm test` through the four corpus fitness fences,
 * which ship the adversarial companions (charter #4). This runner is the
 * human-readable CI report - the same runner/fence split as `golden-cases`.
 */
import { SIGNOFF_PENDING } from "./corpus/signoff";
import { validateCorpus } from "./corpus/validate";

const useColor = process.env.NO_COLOR === undefined;
const paint = (code: string, s: string) => (useColor ? `\u001b[${code}m${s}\u001b[0m` : s);
const green = (s: string) => paint("32", s);
const red = (s: string) => paint("31;1", s);
const dim = (s: string) => paint("2", s);
const bold = (s: string) => paint("1", s);

const result = validateCorpus();
const defects = result.cases.filter((item) => item.label.kind === "defect").length;
const controls = result.cases.length - defects;

console.log(bold(`\nREPLAY CORPUS - the prompt-11 synthetic substrate (${result.cases.length} case(s))`));
console.log(dim("labels are author-invented and SYNTHETIC; they are not evidence that any defect has occurred\n"));
console.log(`  corpusVersion   ${result.spec.world.corpusVersion}`);
console.log(`  corpusDigest    ${result.corpusDigest}`);
console.log(`  signoff         ${result.signoff.status ?? "(missing)"}`);
console.log(`  synthetic       ${defects} defect case(s) + ${controls} labeled clean control(s)`);
console.log(`  real-derived    0 case(s) ${dim("- deferred pending an authorized scrubbed source (ADR-0034)")}\n`);

for (const problem of result.problems) console.log(red(`  ✗ ${problem}`));

if (result.problems.length > 0) {
  console.error(red(`\ncorpus: ${result.problems.length} problem(s) - a hand-edited or drifted corpus cannot pass (charter #4)\n`));
  process.exit(1);
}

console.log(green(`corpus: regenerated byte-identical; every rule holds`));
if (result.signoff.status === SIGNOFF_PENDING) {
  console.log(dim("no figure is reported until the captain signs this corpus version (pnpm corpus:report)\n"));
} else {
  console.log(dim(`signed against corpusDigest ${result.signoff.signedDigest}\n`));
}
