/**
 * POPULATED-WORLD VALIDATION RUNNER (ADR-0057; blocking CI job `world`) -
 * `pnpm world:validate`.
 *
 * Regenerates the world from the hand-owned spec, byte-compares it against the
 * committed tree, and re-checks every world rule: fixture provenance on every
 * record, no pre-computed health score, no observation in the future, holdings
 * that reconcile to their account balance, the deliberate surname collisions,
 * and cross-household links acknowledged from both sides.
 *
 * The same core runs inside `pnpm test` through the world fitness fences, which
 * ship the adversarial companions (charter #4). This runner is the
 * human-readable CI report - the same runner/fence split as `corpus`.
 */
import { errorMessage } from "./error-message";
import { validateWorld } from "./world/validate";

const useColor = process.env.NO_COLOR === undefined;
const paint = (code: string, s: string) => (useColor ? `\u001b[${code}m${s}\u001b[0m` : s);
const green = (s: string) => paint("32", s);
const red = (s: string) => paint("31;1", s);
const dim = (s: string) => paint("2", s);
const bold = (s: string) => paint("1", s);

try {
  const result = validateWorld();
  const handAuthored = result.world.households.filter((household) => household.authoring === "hand-authored").length;
  const accounts = result.world.households.reduce((sum, household) => sum + household.accounts.length, 0);
  const people = result.world.households.reduce((sum, household) => sum + household.members.length, 0);
  console.log(bold(`\nPOPULATED WORLD - ${result.world.households.length} named households`));
  console.log(dim("every record is labeled source=fixture; nothing here may feed a compliance decision (charter #3)\n"));
  console.log(`  worldVersion  ${result.spec.roster.worldVersion}`);
  console.log(`  worldDigest   ${result.worldDigest}`);
  console.log(`  authoring     ${handAuthored} hand-authored, ${result.world.households.length - handAuthored} derived`);
  console.log(`  depth         ${people} people, ${accounts} accounts\n`);

  for (const problem of result.problems) console.log(red(`  ✗ ${problem}`));
  if (result.problems.length > 0) {
    console.error(red(`\nworld: ${result.problems.length} problem(s) - a hand-edited or drifted world cannot pass (charter #4)\n`));
    process.exit(1);
  }
  console.log(green("world: regenerated byte-identical; every rule holds\n"));
} catch (e) {
  console.error(red(`world validation failed: ${errorMessage(e)}`));
  process.exit(1);
}
